In [1]:
import pandas as pd

In [2]:
#load Jersey City csvs from https://s3.amazonaws.com/tripdata/index.html
JC_data_Jan = pd.read_csv("JC-201901-citibike-tripdata.csv")
JC_data_Feb = pd.read_csv("JC-201902-citibike-tripdata.csv")
JC_data_Mar = pd.read_csv("JC-201903-citibike-tripdata.csv")
JC_data_Apr = pd.read_csv("JC-201904-citibike-tripdata.csv")
JC_data_May = pd.read_csv("JC-201905-citibike-tripdata.csv")
JC_data_Jun = pd.read_csv("JC-201906-citibike-tripdata.csv")
JC_data_July = pd.read_csv("JC-201907-citibike-tripdata.csv")
JC_data_Aug = pd.read_csv("JC-201908-citibike-tripdata.csv")

In [10]:
#combine the csvs
total_2019_JC = pd.concat([JC_data_Jan, JC_data_Feb, JC_data_Mar, JC_data_Apr,JC_data_May, JC_data_Jun, JC_data_July,JC_data_Aug])
total_2019_JC

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48706,384,2019-08-31 23:40:45.2450,2019-08-31 23:47:09.8810,3639,Harborside,40.719252,-74.034234,3203,Hamilton Park,40.727596,-74.044247,29522,Subscriber,1988,1
48707,633,2019-08-31 23:45:55.6660,2019-08-31 23:56:29.5350,3186,Grove St PATH,40.719586,-74.043117,3185,City Hall,40.717733,-74.043845,29679,Customer,1997,1
48708,324,2019-08-31 23:50:27.9220,2019-08-31 23:55:52.8420,3276,Marin Light Rail,40.714584,-74.042817,3211,Newark Ave,40.721525,-74.046305,26198,Subscriber,1997,2
48709,126,2019-08-31 23:52:21.9250,2019-08-31 23:54:28.5820,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,29512,Subscriber,1998,1
48710,690,2019-08-31 23:56:55.1530,2019-09-01 00:08:25.2370,3185,City Hall,40.717733,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,26223,Subscriber,1992,1

In [11]:
# output to a csv to load into Tableau
total_2019_JC.to_csv("Combined_JC_2019.csv")