In [1]:
import pandas as pd

In [3]:
#load in Jersey City csvs from https://s3.amazonaws.com/tripdata/index.html
JC_data_Jan = pd.read_csv("JC-202001-citibike-tripdata.csv")
JC_data_Feb =pd.read_csv("JC-202002-citibike-tripdata.csv")
JC_data_Mar =pd.read_csv("JC-202003-citibike-tripdata.csv")
JC_data_Apr =pd.read_csv("JC-202004-citibike-tripdata.csv")
JC_data_May =pd.read_csv("JC-202005-citibike-tripdata.csv")
JC_data_Jun =pd.read_csv("JC-202006-citibike-tripdata.csv")
JC_data_July =pd.read_csv("JC-202007-citibike-tripdata.csv")
JC_data_Aug =pd.read_csv("JC-202008-citibike-tripdata.csv")

In [18]:
#combine csvs
total_2020_JC = pd.concat([JC_data_Jan, JC_data_Feb, JC_data_Mar, JC_data_Apr,JC_data_May, JC_data_Jun, JC_data_July,JC_data_Aug])
total_2020_JC

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43262,162,2020-08-31 23:43:15.8540,2020-08-31 23:45:58.4550,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,44787,Subscriber,1977,1
43263,400,2020-08-31 23:46:19.9130,2020-08-31 23:53:00.3610,3481,York St,40.716490,-74.041050,3187,Warren St,40.721124,-74.038051,19153,Subscriber,1986,1
43264,288,2020-08-31 23:47:16.8680,2020-08-31 23:52:05.5550,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,42434,Subscriber,1960,1
43265,199,2020-08-31 23:50:37.2650,2020-08-31 23:53:56.9490,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,44226,Subscriber,1994,1
43266,333,2020-08-31 23:55:30.8050,2020-09-01 00:01:04.4110,3211,Newark Ave,40.721525,-74.046305,3270,Jersey & 6th St,40.725289,-74.045572,42437,Subscriber,1984,2

In [19]:
#output to csv for load into Tableau
total_2020_JC.to_csv("Combined_JC_2020.csv")