In [1]:
import pandas as pd

In [7]:
#load in previously created csv
JC_data_2019 = pd.read_csv("Combined_JC_2019.csv")
JC_data_2019

,Unnamed: 0,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262920,48706,384,2019-08-31 23:40:45.2450,2019-08-31 23:47:09.8810,3639,Harborside,40.719252,-74.034234,3203,Hamilton Park,40.727596,-74.044247,29522,Subscriber,1988,1
262921,48707,633,2019-08-31 23:45:55.6660,2019-08-31 23:56:29.5350,3186,Grove St PATH,40.719586,-74.043117,3185,City Hall,40.717732,-74.043845,29679,Customer,1997,1
262922,48708,324,2019-08-31 23:50:27.9220,2019-08-31 23:55:52.8420,3276,Marin Light Rail,40.714584,-74.042817,3211,Newark Ave,40.721525,-74.046305,26198,Subscriber,1997,2
262923,48709,126,2019-08-31 23:52:21.9250,2019-08-31 23:54:28.5820,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,29512,Subscriber,1998,1
262924,48710,690,2019-08-31 23:56:55.1530,2019-09-01 00:08:25.2370,3185,City Hall,40.717732,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,26223,Subscriber,1992,1

In [6]:
#load in previously created csv
JC_data_2020 = pd.read_csv("Combined_JC_2020.csv")
JC_data_2020

,Unnamed: 0,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219909,43262,162,2020-08-31 23:43:15.8540,2020-08-31 23:45:58.4550,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,44787,Subscriber,1977,1
219910,43263,400,2020-08-31 23:46:19.9130,2020-08-31 23:53:00.3610,3481,York St,40.716490,-74.041050,3187,Warren St,40.721124,-74.038051,19153,Subscriber,1986,1
219911,43264,288,2020-08-31 23:47:16.8680,2020-08-31 23:52:05.5550,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,42434,Subscriber,1960,1
219912,43265,199,2020-08-31 23:50:37.2650,2020-08-31 23:53:56.9490,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,44226,Subscriber,1994,1
219913,43266,333,2020-08-31 23:55:30.8050,2020-09-01 00:01:04.4110,3211,Newark Ave,40.721525,-74.046305,3270,Jersey & 6th St,40.725289,-74.045572,42437,Subscriber,1984,2

In [4]:
#combine datasets
total_2019_2020_JC = pd.concat([JC_data_2019,JC_data_2020])
total_2019_2020_JC

,Unnamed: 0,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219909,43262,162,2020-08-31 23:43:15.8540,2020-08-31 23:45:58.4550,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,44787,Subscriber,1977,1
219910,43263,400,2020-08-31 23:46:19.9130,2020-08-31 23:53:00.3610,3481,York St,40.716490,-74.041050,3187,Warren St,40.721124,-74.038051,19153,Subscriber,1986,1
219911,43264,288,2020-08-31 23:47:16.8680,2020-08-31 23:52:05.5550,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,42434,Subscriber,1960,1
219912,43265,199,2020-08-31 23:50:37.2650,2020-08-31 23:53:56.9490,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,44226,Subscriber,1994,1
219913,43266,333,2020-08-31 23:55:30.8050,2020-09-01 00:01:04.4110,3211,Newark Ave,40.721525,-74.046305,3270,Jersey & 6th St,40.725289,-74.045572,42437,Subscriber,1984,2

In [5]:
#output csv for load into Tableau
total_2019_2020_JC.to_csv("Combined_JC_2019_2020.csv")